language: python

python:
    - "3.5"

sudo: false

env:

matrix:
    fast_finish: true

install:
    - pip install -r requirements/devel.txt

script:
    - pytest

after_success:

notifications:
    email: true
